CICD: Combined the build and release workflow. We build, test, and run sonar code analysis for every push/PR but we will only kick off a release for versioned tags. The SemVer versioned tag allows us to link every release back to the exact version of the code that was built and deployed.

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -1,9 +1,16 @@
-name: Release
+name: CI/CD Pipeline
 
 on:
   push:
+    branches:
+      - '*'
     tags:
-      - 'v*'
+      - '*'
+  pull_request:
+    branches:
+      - '*'
+  workflow_dispatch:
+
 env:
   # Stop wasting time caching packages
   DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
@@ -11,20 +18,6 @@ env:
   DOTNET_CLI_TELEMETRY_OPTOUT: true
   DOTNET_NOLOGO: true    
 jobs:
-  prepare:
-    name: Prepare (get version from tag)
-    runs-on: ubuntu-latest
-    timeout-minutes: 2
-    steps:
-    - id: GetBuildVersion
-      run: |
-        $ref = "${env:GITHUB_REF}"
-        $version = $ref.Substring($ref.LastIndexOf("/") + 2)
-        echo "version=${version}" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append 
-        echo "::set-output name=version::${version}"
-      shell: pwsh
-    outputs:
-      version: ${{ steps.GetBuildVersion.outputs.version }}
 
   build-and-test:
     name: Build and Run Tests
@@ -75,11 +68,61 @@ jobs:
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
+  super-linter:
+    # Set the agent to run on
+    runs-on: ubuntu-latest
+
+    ##################
+    # Load all steps #
+    ##################
+    steps:
+    ##########################
+    # Checkout the code base #
+    ##########################
+    - name: Checkout Code
+      uses: actions/checkout@v3
+      with:
+        # Full git history is needed to get a proper list of changed files within `super-linter`
+        fetch-depth: 0
+    ################################
+    # Run Linter against code base #
+    ################################
+    - name: Lint Code Base
+      id: lintcodebase
+      uses: github/super-linter@v4
+      continue-on-error: true  # Informational, continue with pipeline if superlinter fails. 
+      env:
+        VALIDATE_ALL_CODEBASE: false
+        VALIDATE_JSCPD: false
+        VALIDATE_GITHUB_ACTIONS: false
+        # Change to 'master' if your main branch differs
+        DEFAULT_BRANCH: main
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    - name: Check on failures  # Informational, continue with pipeline if superlinter fails.
+      if: steps.lintcodebase.outcome != 'success'
+      run: exit 1
+
+  prepare:
+    name: Prepare (get version from release tag)
+    if: startsWith(github.ref, 'refs/tags/v')
+    runs-on: ubuntu-latest
+    timeout-minutes: 2
+    steps:
+    - id: GetBuildVersion
+      run: |
+        $ref = "${env:GITHUB_REF}"
+        $version = $ref.Substring($ref.LastIndexOf("/") + 2)
+        echo "version=${version}" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append 
+        echo "::set-output name=version::${version}"
+      shell: pwsh
+    outputs:
+      version: ${{ steps.GetBuildVersion.outputs.version }}
+
   publish:
     name: Create deploy package
     needs: [prepare, code-analysis]
     runs-on: ubuntu-latest
-    timeout-minutes: 6
+    timeout-minutes: 10
     steps:
     - uses: actions/checkout@v3
     - name: Setup .NET
@@ -197,6 +240,7 @@ jobs:
     name: Deploy to AWS Production
     needs: [prepare, deploy-staging]
     runs-on: ubuntu-latest
+    timeout-minutes: 20
     environment:
       name: Production
       url: 'https://api.theworkbook.ie/swagger/'
